services:
  - type: web
    name: multi-stock-logistics-platform
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn greaterwms.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: greaterwms.settings
      - key: PYTHON_VERSION
        value: 3.11
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
